[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cae-utils-trier"
version = "1.0.0rc1"
dependencies = [
    "cae-utils-mapped-exceptions==1.0.0rc4"
]
description = "Trier utility library for Python"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.10"
authors = [
  { name = "Ze Lucio Jr" }
]
keywords = ["retries", "exception-handling", "mapped-exceptions", "trier", "cae", "utils"]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: Apache Software License",
  "Operating System :: OS Independent"
]

[project.urls]
Homepage = "https://github.com/clean-arch-enablers-project/cae-utils-trier"
Repository = "https://github.com/clean-arch-enablers-project/cae-utils-trier"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"cae_mapped_exceptions" = ["py.typed"]